---
title: "test_driving_map"
author: "Calum Nicholson"
date: "26/02/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinydashboard)
library(tidyverse)
library(scales)
library(lubridate)
library(ggplot2)
library(rgdal)
library(sp)
library(sf)
library(leaflet)
library(leaflet.extras)

```


``` {r}
# Path to ACHD database data (note: only accessible at RPAH)
pt_data <- 'Z:/CURRENT_STUDIES/2020_achd_map'

# Path to the study's data folder
app_data <- '../ACHD_Dashboard/data/'

```


``` {r}
################################## LOAD DATA ############################################

#import ACHD data
achd <- readRDS(file = paste(pt_data, 'output/rpah_analysis_dataset.rds', sep=""))

#import DX coding
dx_codes <- read.csv(file = paste(app_data, '/ACHD_EPCC_coding.csv', sep=""), fileEncoding="UTF-8-BOM") %>% 
            filter(!(Variable == 'adm_AbsentPA' | Variable == 'PA' | Variable == "achd_id")) %>%
            select(!c(ACHD_Database_name, check., Variable))

#import Census data
sa2.TB <- readRDS(file = paste(app_data, '/sa2_demographics.rds', sep="")) %>%
                            mutate(IRSD = ordered(IRSD, c(1,2,3,4,5,6,7,8,9,10)),
                                   IRSAD = ordered(IRSAD, c(1,2,3,4,5,6,7,8,9,10)))

#import htt data
htt.nsw <- readRDS(file = paste(app_data, '/htt_nsw.rds', sep=""))
htt.details <- readRDS(file = paste(app_data, '/htt_details.rds', sep=""))

#current achd clinics
achd_ids <- c(646, 755, 152, 683, 737, 979)
#placeholer for adding new clinics
new_achd_ids <- achd_ids

#Import area polygons
sa2.polys <- readOGR(paste(app_data, 'ASGS/sa2/sa2_polys.shp', sep=""))

```

``` {r}

prepare.area.data <- function(achd_data) {
    # Diagnosis severity counts in each area
    beth.drive <- achd_data %>%
        group_by(sa2) %>%
        dplyr::summarise(ACHD_count = n(), 
                         beth_1 = sum(bethesda_code == 1),
                         beth_2 = sum(bethesda_code == 2), 
                         beth_3 = sum(bethesda_code == 3), 
                         beth_4 = sum(bethesda_code == 4),
                         ltf_3 = sum(ltf_3),
                         ltf_4 = sum(ltf_4),
                         ltf_5 = sum(ltf_5))
        
    
    # Diagnoses present in each area 
    dx.drive <- achd_data %>%
        mutate_at(as.character(dx_codes[['EPCC_Code']]), as.character) %>% 
        mutate_at(as.character(dx_codes[['EPCC_Code']]), as.numeric) %>%
        group_by(sa2) %>% 
        summarise_at(as.character(dx_codes[['EPCC_Code']]), sum, na.rm = TRUE)
    
    # Join above to table builer data
    area.drive <- left_join(sa2.TB, beth.drive, by = c('SA2_NAME' = 'sa2')) %>% 
        left_join(dx.drive, by = c('SA2_NAME' = 'sa2')) %>%
        mutate_at(as.character(dx_codes[['EPCC_Code']]), function(x) replace(x, is.na(x), 0)) %>%
        mutate_at(c('ACHD_count', 'beth_1', 'beth_2', 'beth_3', 'beth_4',
                    'ltf_3', 'ltf_4', 'ltf_5'), function(x) replace(x, is.na(x), 0))
    
    area.drive
    }




```

``` {r}
area.achd <- prepare.area.data(achd)
```

``` {r}

id_list_1 <- list("11205", "11202", "11203")
id_list_2 <- list("11204", "11103")

```

``` {r}
area.report.list <- list()

```

``` {r}
if ( !(Position(function(x) identical(x, id_list_1), area.report.list, nomatch = 0) > 0)  )
{ area.report.list[[length(area.report.list) + 1]] <- id_list_1 }
area.report.list
```

``` {r}
if ( !(Position(function(x) identical(x, id_list_1), area.report.list, nomatch = 0) > 0) )
{ area.report.list[[length(area.report.list) + 1]] <- id_list_1 }
area.report.list
```

``` {r}
if ( !(Position(function(x) identical(x, id_list_2), area.report.list, nomatch = 0) > 0)  )
{ area.report.list[[length(area.report.list) + 1]] <- id_list_2 }
area.report.list
```

``` {r}
if ( !(Position(function(x) identical(x, id_list_2), area.report.list, nomatch = 0) > 0) )
{ area.report.list[[length(area.report.list) + 1]] <- id_list_2 }
area.report.list
```

``` {r}
id_list <- c(id_list, 11189)

```

``` {r}
id_list <- c(id_list, 11187)

```

``` {r}
id_list <- c(id_list, 11062)

```

``` {r}

event.area <- area.achd %>% filter(SA2_5DIGIT %in% id_list_1)

```

``` {r}
event.area$SA2_NAME
```

``` {r}
paste("Selected Areas: ", paste(event.area$SA2_NAME, collapse = ', '), sep = "")
paste("Number of ACHD Patients: ", sum(event.area$ACHD_count), sep = "")
paste(
"<b>Index of Relative Socio-economic Disadvantage</b><br>
            (1 = most disadvantaged, 10 = least disadvantaged): <br>
            <ul>",
              paste("<li>", event.area$SA2_NAME, ": ", event.area$IRSD, "</li>", collapse = ""),
            "</ul>"
)

```

``` {r}
HTML(
  "<b>Driving time to nearest clinic:</b><br> 
      <ul>",
          paste("<li>",event.area$SA2_NAME,":</li>  
             <ul>
                <li>Current Locations: ", round(as.numeric(event.area$shortest_time, 'hours'), digits = 2)," hrs</li>
                <li>New Locations: ", round(as.numeric(event.area$shortest_time, 'hours'), digits = 2)," hrs</li>
             </ul>", collapse = ""),   
      "</ul>
  "
)

round(as.numeric(drive.area.achd()$shortest_time[drive.area.achd()$SA2_5DIGIT %in% drive.values$map.clicks]), digits = 2)

```

``` {r}
"<b>Driving time to nearest clinic:</b><br> 
            <ul>
                <li>Current Locations:",round(as.numeric(drive.area.achd()$shortest_time[drive.area.achd()$SA2_NAME == drive.values$event_area$SA2_NAME], 'hours'), digits = 2)," hrs</li>
                <li>With New Locations:",round(as.numeric(drive.values$event_area$shortest_time, 'hours'), digits = 2)," hrs</li>"
```

``` {r}
# driving time of selected areas
range(as.numeric(event.area$shortest_time, 'hours'))
# Shortest dricing time of areas
min(as.numeric(event.area$shortest_time, 'hours'))

as.numeric(area.achd$shortest_time[area.achd$SA2_5DIGIT %in% id_list], 'hours')
```


``` {r}
# Some area level demographics to display
no.areas <- area.achd %>% nrow()

no.areas.syd <- area.achd %>% filter(GCC_NAME == "Greater Sydney") %>% nrow()

no.areas.nsw <- area.achd %>% filter(GCC_NAME == "Rest of NSW") %>% nrow()

no.areas.act <- area.achd %>% filter(GCC_NAME == "Australian Capital Territory") %>% nrow()

avg.drive <- area.achd %>% 
                    summarise(st_avg = mean(as.numeric(shortest_time, 'hours'), na.rm = TRUE)) %>%
                    pull(st_avg)

avg.drive.syd <- area.achd %>% 
                    filter(GCC_NAME == "Greater Sydney") %>%
                    summarise(st_avg = mean(as.numeric(shortest_time, 'hours'), na.rm = TRUE)) %>%
                    pull(st_avg)

avg.drive.nsw <- area.achd %>% 
                    filter(GCC_NAME == "Rest of NSW") %>%
                    summarise(st_avg = mean(as.numeric(shortest_time, 'hours'), na.rm = TRUE)) %>%
                    pull(st_avg)

avg.drive.act <- area.achd %>% 
                    filter(GCC_NAME == "Australian Capital Territory") %>%
                    summarise(st_avg = mean(as.numeric(shortest_time, 'hours'), na.rm = TRUE)) %>%
                    pull(st_avg)

no.hr <- area.achd %>% filter(as.numeric(shortest_time, "hours") <= 1) %>%
                       nrow()

no.hr.syd <- area.achd %>% 
                       filter(GCC_NAME == "Greater Sydney") %>%
                       filter(as.numeric(shortest_time, "hours") <= 1) %>%
                       nrow()

no.hr.nsw <- area.achd %>% 
                       filter(GCC_NAME == "Rest of NSW") %>%
                       filter(as.numeric(shortest_time, "hours") <= 1) %>%
                       nrow()

no.hr.act <- area.achd %>% 
                       filter(GCC_NAME == "Australian Capital Territory") %>%
                       filter(as.numeric(shortest_time, "hours") <= 1) %>%
                       nrow()


```


``` {r}
area.summary <- data.frame(
  no.areas = c(no.areas, no.areas.syd, no.areas.nsw, no.areas.act),
  n.area.hr = c(no.hr, no.hr.syd, no.hr.nsw, no.hr.act),
  avg.drive = c(avg.drive, avg.drive.syd, avg.drive.nsw, avg.drive.act),
  row.names = c("All", "Greater Sydney", "Rest of New South Wales", "ACT")
)


```


``` {r}
library(gt)
library(kableExtra)

gt(area.summary)
kbl(area.summary, 
    booktabs = T,
    col.names = c("No. of Areas",
                  "No. Areas < 1hr Drive",
                  "Average Driving Time"))


```



``` {r}

coords <- coordinates(sa2.polys) %>%
            as.data.frame()  %>%
            rename("long" = "V1",
                   "lat" = "V2")

```

``` {r}
max(sa2.polys@polygons[[1]]@Polygons[[1]]@coords[,1])



```

``` {r}
coords <- do.call(rbind,lapply(sa2.polys@polygons, function(x) 
        {data.frame(long = c(min(x@Polygons[[1]]@coords[,1]),
                            max(x@Polygons[[1]]@coords[,1])),
                    lat = c(min(x@Polygons[[1]]@coords[,2]),
                            max(x@Polygons[[1]]@coords[,2]))
                    )
        })
)
```

``` {r}

min(coords$long)
min(coords$lat)
max(coords$long)
max(coords$lat)

```


``` {r}
achd_ids <- c(152, 408, 646, 683, 737, 979)

new_achd_ids <- achd_ids
```


``` {r}
add.id <- function(id, id_list) {
if (!(id %in% id_list)) { id_list <- append(id_list, id) }
  
  id_list
}

reset.ids <- function(original_ids, id_list) {
  id_list <- original_ids
  
  id_list
}
```


``` {r}
new_achd_ids <- add.id(472, new_achd_ids)
new_achd_ids <- add.id(107, new_achd_ids)
new_achd_ids <- add.id(332, new_achd_ids)
```

``` {r}
shortest_time_new <- htt.nsw %>%
                select(SA2_5DIGIT, as.character(new_achd_ids)) %>%
                mutate(shortest_time = pmap_dbl(
                                           .l = select(., -SA2_5DIGIT),
                                           .f = function(...) min(...)
                                         ),
                       shortest_time = duration(shortest_time, "seconds")) %>%
                select(SA2_5DIGIT, shortest_time)
```

``` {r}
area.achd.new <- area.achd %>%
                    select(-shortest_time) %>%
                    left_join(shortest_time_new, by = "SA2_5DIGIT")
```

``` {r}
hospital_id <- 331


selected_hospital <- htt.nsw %>%
        select(SA2_5DIGIT, as.character(hospital_id)) %>%
        mutate(hospital = as.duration(.[[as.character(hospital_id)]])) %>%
        left_join(area.achd, by ='SA2_5DIGIT') %>%
        select(hospital, sa2_area, SA2_5DIGIT, ACHD_count, ltf_3, beth_1, beth_2, beth_3)


```

``` {r}
current_hospitals <- htt.nsw %>%
        select(SA2_5DIGIT, as.character(achd_ids)) %>%
        mutate_at(as.character(achd_ids), as.duration) %>%
        left_join(area.achd, by ='SA2_5DIGIT') %>%
        select(as.character(achd_ids), sa2_area, SA2_5DIGIT, ACHD_count, ltf_3, beth_1, beth_2, beth_3)
```

``` {r}
current_hospitals_table <- data.frame(Hospital = htt.details %>% filter(Hospital_ID %in% achd_ids) %>% 
                                                                 pull(Hospital.name),
                                      ID = htt.details %>% filter(Hospital_ID %in% achd_ids) %>% 
                                                                 pull(Hospital_ID),
                                      Patients = sapply(achd_ids, function(x)
                                                                  current_hospitals %>% 
                                                                  filter(as.numeric(!!as.symbol(x), "hours") <= 1) %>%
                                                                  summarise(hr_drive = sum(ACHD_count)) %>%
                                                                  pull(hr_drive)
                                                   ),
                                      ltf = sapply(achd_ids, function(x)
                                                                  current_hospitals %>% 
                                                                  filter(as.numeric(!!as.symbol(x), "hours") <= 1) %>%
                                                                  summarise(hr_drive = sum(ltf_3)) %>%
                                                                  pull(hr_drive)
                                                   ),
                                      stringsAsFactors = FALSE)

```

``` {r}
current_hospitals %>% filter(as.numeric(!!as.symbol(737), "hours") <= 1) %>%
                                                         summarise(hr_drive = sum(ltf_3)) %>%
                                                         pull(hr_drive)
```


``` {r}
new_achd_ids <- reset.ids(achd_ids, new_achd_ids)
```

``` {r}
area.achd.new <- area.achd
```

``` {r}
test <- cbind(area.achd$shortest_time, area.achd.new$shortest_time) %>%
          as.data.frame() %>%
          mutate(diff = V1 - V2)
```


``` {r}
new.hosp.df <- data.frame(Hospital = as.character(), ID = as.numeric(), stringsAsFactors = FALSE)

new.row <- data.frame(Hospital = htt.details$Hospital.name[htt.details$Hospital_ID == 472], ID = 472, stringsAsFactors = FALSE)

```

``` {r}
rbind(new.hosp.df, new.row)


```


``` {r}
new.hosp.df[nrow(new.hosp.df)+1,] <- c(htt.details$Hospital.name[htt.details$Hospital_ID == 472], 472)
```

``` {r}
new.hosp.df[nrow(new.hosp.df)+1,] <- c(htt.details$Hospital.name[htt.details$Hospital_ID == 107], 107)

```

``` {r}
new.hosp.df[nrow(new.hosp.df)+1,] <- c(htt.details$Hospital.name[htt.details$Hospital_ID == 332], 332)

```

``` {r}
gcc.filt <- area.achd.new %>% filter(GCC_NAME == 'Greater Sydney')


```


``` {r}
seq(0, 
    plyr::round_any(max(as.numeric(gcc.filt$shortest_time, 'hours'), na.rm = TRUE), 1, ceiling), 
    plyr::round_any(max(as.numeric(gcc.filt$shortest_time, 'hours'), na.rm = TRUE), 1, ceiling)/10)

```



``` {r}
       # Creating the driving times map
        output$drive.map <- renderLeaflet({
            leaflet() %>%
                addTiles() %>%
                addPolygons(
                    data = drive.polys(),
                    layerId = ~CODE16,
                    fillColor = ~pal.drive()(as.numeric(drive.polys()$shortest_time, 'hours')),
                    weight = 1,
                    opacity = 1,
                    color = "white",
                    dashArray = "3",
                    fillOpacity = 0.7,
                    highlight = highlightOptions(
                        weight = 3,
                        color = "#666",
                        dashArray = "",
                        fillOpacity = 0.7,
                        bringToFront = TRUE),
                    label = labels.drive(),
                    labelOptions = labelOptions(
                        style = list("font-weight" = "normal", padding = "3px 8px"),
                        textsize = "15px",
                        direction = "auto")) %>%
                addMarkers(
                    data = htt.details %>% filter(Hospital_ID %in% achd_ids),
                    lng = ~Longitude,
                    lat = ~Latitude,
                    label = ~Hospital.name) %>%
                addMarkers(
                    data = htt.details %>% filter(Hospital_ID %in% isolate(drive.values$add_clinic_table[['ID']])),
                    lng = ~Longitude,
                    lat = ~Latitude,
                    label = ~Hospital.name
                ) %>%
                addLegend(pal = pal.drive(), 
                          values = as.numeric(drive.polys()$shortest_time, 'hours'), 
                          opacity = 0.7, 
                          title = "Driving time to clinics",
                          position = "bottomright")
            
        })





```

# apply the area report template for each area
        src <- lapply(drive.values$area.report.list,
                      function(i) knit_expand('Area_Report.Rmd'))
        # render the area reports
        cat(knit(text = src,
                 quiet = TRUE))
