---
title: "Leaflet_test"
author: "Calum Nicholson"
date: "12/08/2020"
output: html_document
---

```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE)
# set 'data' folder as root directory
knitr::opts_knit$set(root.dir = '../..')

library(tidyverse)
library(lubridate)
library(rgdal)
library(sp)
library(sf)
library(leaflet)
library(leaflet.extras)
library(ggplot2)
library(tidyverse)

ACHD_path <- 'Z:/CURRENT_STUDIES/2020_achd_map'
```

```{r}

#import SA2 ACHD data
sa2.count <- readRDS(file = paste(ACHD_path, 'output/sa2.count_2020-10-08.rds', sep=""))

#import SA3 ACHD data
sa3.count <- readRDS(file = paste(ACHD_path, 'output/sa3.count_2020-10-08.rds', sep=""))

#import SA4 ACHD data
sa4.count <- readRDS(file = paste(ACHD_path, 'output/sa4.count_2020-10-08.rds', sep=""))

```



``` {r}
# import the hospital travel times data
htt <- read.csv('../hospital_TT/duration_sa2_hospitals.csv') %>%
#         ------------Clean up the data-------------------------  
          # select columns, sa2 code and ACHD locations          
          select(SA2_5DIG16, time_to_646, time_to_755, time_to_152, 
                 time_to_683, time_to_737, time_to_979) %>%
          # rename locations to something understandable
          rename("time_to_orange" = time_to_646,
                 "time_to_nowra" = time_to_755,
                 "time_to_canberra" = time_to_152,
                 "time_to_port" = time_to_683,
                 "time_to_rpa" = time_to_737,
                 "time_to_westmead" = time_to_979,
                 "SA2_5DIGITCODE_2016" = SA2_5DIG16) %>%
          # calculate the shortest travel time to an achd clinic
          mutate(shortest_time = pmin(time_to_orange,time_to_nowra,time_to_canberra,
                                     time_to_port,time_to_rpa,time_to_westmead))

# Load the list of ASGS SA2 area names and codes and filter for NSW and ACT
SA2_codes <- read.csv('../ASGS/SA2_2016_AUST.csv') %>%
            select(STATE_NAME_2016, SA2_5DIGITCODE_2016, SA2_NAME_2016) %>%
            filter(STATE_NAME_2016 == "New South Wales" | STATE_NAME_2016 == "Australian Capital Territory")
```

``` {r}
# Select the HTT areas from NSW and ACT
HTT_nsw <- left_join(SA2_codes, htt, by = "SA2_5DIGITCODE_2016") %>%
             # Convert the numeric data to duration data (in seconds)
             mutate(time_to_orange = duration(time_to_orange, "seconds"),
                    time_to_nowra = duration(time_to_nowra, "seconds"),
                    time_to_canberra = duration(time_to_canberra, "seconds"),
                    time_to_port = duration(time_to_port, "seconds"),
                    time_to_rpa = duration(time_to_rpa, "seconds"),
                    time_to_westmead = duration(time_to_westmead, "seconds"),
                    shortest_time = duration(shortest_time, "seconds"),)

sa2.data <- left_join(HTT_nsw, sa2.count, by = c("SA2_NAME_2016" = "sa2"))

```


``` {r}
#import SA2 polygon boundaries
sa2.polys <- readOGR('../ASGS/1270055001_sa2_2016_aust_shape/SA2_2016_AUST.shp')
``` 

``` {r}
# filter for NSW and ACT and simplify for faster processing
NSW_sa2 <- subset(sa2.polys, sa2.polys$GCC_NAME16 %in% 
                     c("Rest of NSW", "Greater Sydney", "Australian Capital Territory"))
simple_sa2 <- rgeos::gSimplify(NSW_sa2, tol = 0.01, topologyPreserve=TRUE)

# Add the SA2 code and name to the simplified shapefile
simple_sa2$SA2_5DIG16 <- NSW_sa2$SA2_5DIG16
simple_sa2$SA2_NAME16 <- NSW_sa2$SA2_NAME16

# Select the travel time and ACHD population data
achd.data <- sa2.data %>% select(SA2_5DIGITCODE_2016, shortest_time, ACHD_count)

# Add the ACHD data to the shapefile
simple_sa2 <- merge(simple_sa2, achd.data, by.x = 'SA2_5DIG16', by.y = 'SA2_5DIGITCODE_2016')
```

``` {r}
nsw.data <- NSW_sa2@data %>%
              select(SA2_5DIG16, SA2_NAME16, GCC_NAME16)

#save as csv and r data file
#write.csv(nsw.data, "./achd-dissertation/EDA/output/sa2_GCC_name.csv")
#saveRDS(nsw.data, file = "./achd-dissertation/EDA/output/sa2_GCC_name.rds")


```

``` {r}
getwd()


```


``` {r}
# Select bins for color pallette
bins <- seq(0,11,1)

# Create Colour pallette
pal <- colorBin("YlOrRd", domain = as.numeric(simple_sa2$shortest_time, "hours"), bins = bins)

# Labels for area mouse over
labels <- sprintf(
  "<strong>%s</strong><br/>%g hours by car",
  simple_sa2$SA2_NAME16, as.numeric(simple_sa2$shortest_time, "hours")) %>% lapply(htmltools::HTML)
```



``` {r}
# Plot the driving distance data
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addTiles() %>%
  addPolygons(data = simple_sa2, 
              fillColor = ~pal(as.numeric(simple_sa2$shortest_time, 'hours')),
              weight = 1,
              opacity = 1,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                              weight = 3,
                              color = "#666",
                              dashArray = "",
                              fillOpacity = 0.7,
                              bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                              style = list("font-weight" = "normal", padding = "3px 8px"),
                              textsize = "15px",
                              direction = "auto")) %>%
  addLegend(pal = pal, 
            values = bins, 
            opacity = 0.7, 
            title = "Time to clinic (hrs)",
            position = "bottomright")
```

``` {r}
simple_sa2@data <- simple_sa2@data %>% replace_na(list('ACHD_count' = 0))

plyr::round_any(max(simple_sa2$ACHD_count), 5, ceiling)
```



``` {r}
bins <- seq(plyr::round_any(min(simple_sa2$ACHD_count), 5, floor), 
            plyr::round_any(max(simple_sa2$ACHD_count), 5, ceiling), 
            5)
pal <- colorBin("YlOrRd", domain = simple_sa2$ACHD_count, bins = bins)


labels <- sprintf(
  "<strong>%s</strong><br/>%g ACHD patient in area",
  simple_sa2$SA2_NAME16, simple_sa2$ACHD_count) %>% lapply(htmltools::HTML)
```


``` {r}
# test the polygon in a map
leaflet() %>%
  addTiles() %>%
  addPolygons(data = simple_sa2, 
              fillColor = ~pal(ACHD_count),
              weight = 1,
              opacity = 1,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                              weight = 3,
                              color = "#666",
                              dashArray = "",
                              fillOpacity = 0.7,
                              bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                              style = list("font-weight" = "normal", padding = "3px 8px"),
                              textsize = "15px",
                              direction = "auto")) %>%
  addLegend(pal = pal, 
            values = bins, 
            opacity = 0.7, 
            title = "ACHD population",
            position = "bottomright")
```

``` {r}
sa3.polys <- readOGR('../ASGS/1270055001_sa3_2016_aust_shape/SA3_2016_AUST.shp')
```

``` {r}
#filter for NSW and simplify for faster processing
NSW_sa3 <- subset(sa3.polys, sa3.polys$GCC_NAME16 %in% 
                     c("Rest of NSW", "Greater Sydney", "Australian Capital Territory"))
simple_sa3 <- rgeos::gSimplify(NSW_sa3, tol = 0.01, topologyPreserve=TRUE)

simple_sa3$SA3_CODE16 <- NSW_sa3$SA3_CODE16
simple_sa3$SA3_NAME16 <- NSW_sa3$SA3_NAME16

simple_sa3 <- merge(simple_sa3, sa3.count, by.x = 'SA3_NAME16', by.y = 'sa3')
```

``` {r}
bins <- seq(0, 200, 20)
pal <- colorBin("YlOrRd", domain = simple_sa3$ACHD_count, bins = bins)


labels <- sprintf(
  "<strong>%s</strong><br/>%g ACHD patient in area",
  simple_sa3$SA3_NAME16, simple_sa3$ACHD_count) %>% lapply(htmltools::HTML)
```


``` {r}
# test the polygon in a map
leaflet() %>%
  addTiles %>%
  addPolygons(data = simple_sa3, 
              fillColor = ~pal(ACHD_count),
              weight = 1,
              opacity = 1,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                              weight = 3,
                              color = "#666",
                              dashArray = "",
                              fillOpacity = 0.7,
                              bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                              style = list("font-weight" = "normal", padding = "3px 8px"),
                              textsize = "15px",
                              direction = "auto")) %>%
  addLegend(pal = pal, 
            values = bins, 
            opacity = 0.7, 
            title = "ACHD population",
            position = "bottomright")
```

``` {r}
sa4.polys <- readOGR('../ASGS/1270055001_sa4_2016_aust_shape/SA4_2016_AUST.shp')
```

``` {r}
#filter for NSW and simplify for faster processing
NSW_sa4 <- subset(sa4.polys, sa4.polys$GCC_NAME16 %in% 
                     c("Rest of NSW", "Greater Sydney", "Australian Capital Territory"))
simple_sa4 <- rgeos::gSimplify(NSW_sa4, tol = 0.01, topologyPreserve=TRUE)

simple_sa4$SA4_CODE16 <- NSW_sa4$SA4_CODE16
simple_sa4$SA4_NAME16 <- NSW_sa4$SA4_NAME16

simple_sa4 <- merge(simple_sa4, sa4.count, by.x = 'SA4_NAME16', by.y = 'sa4')
```

``` {r}
bins <- seq(0, 400, 40)
pal <- colorBin("YlOrRd", domain = simple_sa4$ACHD_count, bins = bins)


labels <- sprintf(
  "<strong>%s</strong><br/>%g ACHD patient in area",
  simple_sa4$SA4_NAME16, simple_sa4$ACHD_count) %>% lapply(htmltools::HTML)
```


``` {r}
# test the polygon in a map
leaflet() %>%
  addTiles %>%
  addPolygons(data = simple_sa4, 
              fillColor = ~pal(ACHD_count),
              weight = 1,
              opacity = 1,
              color = "white",
              dashArray = "3",
              fillOpacity = 0.7,
              highlight = highlightOptions(
                              weight = 3,
                              color = "#666",
                              dashArray = "",
                              fillOpacity = 0.7,
                              bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                              style = list("font-weight" = "normal", padding = "3px 8px"),
                              textsize = "15px",
                              direction = "auto")) %>%
  addLegend(pal = pal, 
            values = bins, 
            opacity = 0.7, 
            title = "ACHD population",
            position = "bottomright")
```

