---
title: "&nbsp;"
output: html_document
---
&nbsp;  
&nbsp;  
&nbsp; 

## Area Focus 

``` {r, echo = FALSE}
# Data for the selected areas
selected_areas <- drive.values$area_data %>% filter(SA2_5DIGIT %in% {{i}})
```

<div style= "float:right;
             position: relative;
             ">
``` {r, echo = FALSE}
area.polys <- subset(drive.polys(), drive.polys()$NAME16 %in% selected_areas$SA2_NAME)

# Map highlighting the selected area
leaflet() %>%
            addTiles() %>%
            # Add Polygons
            addPolygons(
                data = area.polys,
                layerId = ~CODE16,
                color = 'black',
                fill = 'white',
                weight = 1,
                highlight = highlightOptions(
                        weight = 3),
                label = area.polys$NAME16,
                labelOptions = labelOptions(
                        style = list("font-weight" = "normal", padding = "3px 8px"),
                        textsize = "15px",
                        direction = "auto"))
```

``` {r, echo = FALSE, fig.width = 7}
# Data of diagnoses present in area
dx.area.data <- selected_areas %>% select(dx_codes$EPCC_Code) %>% 
                            mutate_all(as.character) %>%
                            mutate_all(as.numeric) %>%
                            summarise_all(sum, na.rm = TRUE) %>%
                            t() %>% as.data.frame() %>%
                            rename("dx_count" = V1) %>% 
                            mutate(dx_label = dx_codes$Adjust_name[match(row.names(.), dx_codes$EPCC_Code)]) %>%
                            filter(dx_count > 0)

# Plot of diagnoses present in area
ggplot(data = dx.area.data, aes(x = reorder(dx_label, dx_count), y=dx_count)) + 
              geom_bar(stat="identity") +
              scale_y_continuous(breaks = seq(0, max(dx.area.data$dx_count), 1)) +
              theme(axis.text.x = element_text(angle = 90)) +
              labs(title = "Frequecy of each diagnosis", 
                   y = "count",
                   x = "") +
              coord_flip()
```
</div>

<div style= "font-size: 15px;">
``` {r, echo = FALSE}
HTML(paste(
            "
            <br><br>
            <b>Selected Areas:</b> ", paste(selected_areas$SA2_NAME, collapse = ', '), "<br>
            <br>
            <b>Number of ACHD Patients:</b> ", sum(selected_areas$ACHD_count),"<br>
            <br>
            <b>Number with:</b> <br>
            <ul>
              <li>Simple CHD: ",sum(selected_areas$beth_1),"</li>
              <li>Moderate CHD: ",sum(selected_areas$beth_2),"</li> 
              <li>Complex CHD: ",sum(selected_areas$beth_3),"</li>
            </ul>
            <b>Number of Patients lost to follow up:</b><br> 
            <ul>
              <li>",sum(selected_areas$ltf_3),"</li>
            </ul>
            <b>Index of Relative Socio-economic Disadvantage</b><br>
              (1 = most disadvantaged, 10 = least disadvantaged): <br>
              <ul>",
              paste("<li>", selected_areas$SA2_NAME, ": ", 
                    selected_areas$IRSD, "</li>", collapse = ""),
            "</ul>
            <b>Aboriginal and Torres Strait Islander Population</b><br>
            <ul>
                <li>Total: ",sum(selected_areas$atsi),"</li>
                <li>Percent: ",percent(sum(selected_areas$atsi) / 
                                       sum(selected_areas$total_pop)),"</li>
            </ul>
            <b>Accessibility and Remoteness Index of Australia</b><br>
            (percentage of population living in):<br>  
            <ul>
                <li>Major Cities: ",percent(sum(selected_areas$major_cities) / 
                                    length(selected_areas$SA2_NAME)),"</li>
                <li>Inner Regional:",percent(sum(selected_areas$inner_regional) / 
                                     length(selected_areas$SA2_NAME)),"</li>
                <li>Outer Regional:",percent(sum(selected_areas$outer_regional) / 
                                     length(selected_areas$SA2_NAME)),"</li> 
                <li>Remote:",percent(sum(selected_areas$remote) / 
                             length(selected_areas$SA2_NAME)),"</li>
                <li>Very Remote:",percent(sum(selected_areas$very_remote) / 
                                  length(selected_areas$SA2_NAME)),"</li>
            </ul>
            <b>Driving time to nearest clinic:</b><br> 
            <ul>",
                 paste("<li>",selected_areas$SA2_NAME,":</li>  
                 <ul>
                    <li>Current Locations: ", 
                    round(as.numeric(drive.area.achd()$shortest_time[drive.area.achd()$SA2_5DIGIT %in% {{i}}], 'hours'), 
                    digits = 2)," hrs</li>
                    <li>New Locations: ", 
                    round(as.numeric(selected_areas$shortest_time, 'hours'), digits = 2)," hrs</li>
                 </ul>", collapse = ""),   
            "</ul>
            ")
            )
```
</div>

