
## New ACHD Clinics in NSW

The following clinics were selected as potentials for new locations in NSW

``` {r, echo = FALSE}
# Table displaying info for new clinics
drive.values$add_clinic_table %>%
  # Remove the ID columns
  select(-ID) %>%
  # Add Total Column
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "Total")) %>%
  #Display the table nicely
  kbl(booktabs = T,
      align=c('l','r','r'), # Centre the data
      # Nice Column Names
      col.names = c("New ACHD Clinics",
                  "Patient within 1hr (n)",
                  "Lost to F/up within 1hr (n)"),
      # Table caption
      caption = "\\textbf{Number of patients captured in the new clinics}") %>%
  kable_styling(full_width = F,
                latex_options = c("striped", "hold_position"),
                position = "left"
                )
```

``` {r, echo = FALSE, include = FALSE}
# Table summarising key measures with current clincis only
clinic.compare.current <- data.frame(
                        # Number of patients within a 1 hour drive
                        no_pt = area.achd %>% filter(as.numeric(shortest_time, "hours") <= 1) %>%
                                                                          summarise(no_pt = sum(ACHD_count)),
                        # Number of patients lost to follow up within a 1 hour drive
                        ltf_no = area.achd %>% filter(as.numeric(shortest_time, "hours") <= 1) %>%
                                                                          summarise(ltf_no = sum(ltf_3)),
                        # Average driving time to an ACHD clinic
                        avg_drive = area.achd %>% summarise(avg_drive = mean(as.numeric(shortest_time, 'hours'), 
                                                                             na.rm = TRUE)),
                        # Longest driving time to an ACHD clinic
                        long_drive = area.achd %>% summarise(long_drive = max(as.numeric(shortest_time, 'hours'), 
                                                                             na.rm = TRUE))
                      ) %>% mutate(
                        hr_p = no_pt / sum(area.achd$ACHD_count), # Percentage of patients within 1 hour
                        ltf_p = ltf_no / sum(area.achd$ltf_3) # Perc of LTF patients within 1 hour
                      ) %>%
                      select(no_pt, hr_p, ltf_no, ltf_p, avg_drive, long_drive) # Put the columns in the right order

# Table summarising key measures with current and new clincis                                                    
clinic.compare.new <- data.frame(
                        # Number of patients within a 1 hour drive
                        no_pt = drive.polys()@data %>% filter(as.numeric(shortest_time, "hours") <= 1) %>%
                                                                          summarise(no_pt = sum(ACHD_count)),
                        # Number of patients lost to follow up within a 1 hour drive
                        ltf_no = drive.polys()@data %>% filter(as.numeric(shortest_time, "hours") <= 1) %>%
                                                                          summarise(ltf_no = sum(ltf_3)),
                        # Average driving time to an ACHD clinic
                        avg_drive = drive.polys()@data %>% summarise(avg_drive = mean(as.numeric(shortest_time, 'hours'), 
                                                                             na.rm = TRUE)),
                        # Longest driving time to an ACHD clinic
                        long_drive = drive.polys()@data %>% summarise(long_drive = max(as.numeric(shortest_time, 'hours'), 
                                                                             na.rm = TRUE))
                      ) %>% mutate(
                        hr_p = no_pt / sum(drive.polys()@data$ACHD_count), # Percentage of patients within 1 hour
                        ltf_p = ltf_no / sum(drive.polys()@data$ltf_3) # Perc of LTF patients within 1 hour
                      ) %>%
                      select(no_pt, hr_p, ltf_no, ltf_p, avg_drive, long_drive) # Put the columns in the right order

# Table summarising the difference between the current clinic and new clinic measures
diff <- data.frame(
  no_pt = clinic.compare.new$no_pt - clinic.compare.current$no_pt,
  hr_p = clinic.compare.new$hr_p - clinic.compare.current$hr_p,
  ltf_no = clinic.compare.new$ltf_no - clinic.compare.current$ltf_no,
  ltf_p = clinic.compare.new$ltf_p - clinic.compare.current$ltf_p,
  avg_drive = clinic.compare.new$avg_drive - clinic.compare.current$avg_drive,
  long_drive = clinic.compare.new$long_drive - clinic.compare.current$long_drive
)

# Add all the row together into 1 table
clinic.compare <- rbind(clinic.compare.current, clinic.compare.new, diff) %>%
                          mutate(hr_p = round(hr_p * 100, digits = 2),
                                 ltf_p = round(ltf_p * 100, digits = 2),
                                 avg_drive = round(avg_drive, digits = 2),
                                 long_drive = round(long_drive, digits = 2)
                                 )

row.names(clinic.compare) <- c("Current Clincs Locations", "New Clinics Locations", "Difference")

```


``` {r, echo = FALSE}
# Display the table nicely
clinic.compare %>%
  kbl(booktabs = T,
      align=rep('r', 6), # Centre the data
      # Make nice column names
      col.names = c("Patients within 1hr (n)",
                    "Patients within 1hr (%)",
                    "Lost to F/up within 1hr (n)",
                    "Lost to F/up within 1hr (%)",
                    "Average Drive to ACHD Clinic (hrs)",
                    "Longest Drive to ACHD Clinic (hrs)"),
      # Table caption
      caption = "\\textbf{Comparing the reach of current ACHD clinic locations to
                                  new ACHD clinic locations}") %>%
  kable_styling(full_width = F,
                latex_options = c("striped", "hold_position"),
                position = "left"
                ) %>%
        column_spec(column = 1, width = "2cm") %>% 
        column_spec(column = 2, width = "2cm") %>% 
        column_spec(column = 3, width = "2cm") %>% 
        column_spec(column = 4, width = "2cm") %>% 
        column_spec(column = 5, width = "2cm") %>% 
        column_spec(column = 6, width = "2cm") %>% 
        column_spec(column = 7, width = "2cm")
```




``` {r, include = FALSE, echo = FALSE }
# Table Summarising the Patient data
pt.summary.compare <- data.frame(
                        # Total number of patients
                        no.patient = achd %>% summarise(
                                                    achd.no = n(), # All Patients
                                                    syd.no = sum(gcc == "Greater Sydney"), # Sydney
                                                    nsw.no = sum(gcc == "Rest of NSW"), # NSW
                                                    act.no = sum(gcc == "Australian Capital Territory") # ACT
                                                  ) %>% t(),
                        # Number of Patients within 1 hour drive - current clinics
                        hr.patient.old = area.achd %>% filter(as.numeric(shortest_time, "hours") <= 1) %>%
                                                    summarise(
                                                    hr.no = sum(ACHD_count), # All Patients
                                                    hr.syd = sum(ACHD_count[GCC_NAME == "Greater Sydney"]), # Sydney
                                                    hr.nsw = sum(ACHD_count[GCC_NAME == "Rest of NSW"]), # NSW
                                                    hr.act = sum(ACHD_count[GCC_NAME == "Australian Capital Territory"]) # ACT
                                                    ) %>% t(),
                        # Average driving time to an ACHD clinic - current clinics
                        avg_drive.old = area.achd %>% mutate(shortest_time = as.numeric(shortest_time, 'hours')) %>%
                                                           summarise(avg_drive.all = mean(shortest_time, na.rm = TRUE),
                                                                     avg_drive.syd = mean(shortest_time[GCC_NAME == "Greater Sydney"],
                                                                                          na.rm = TRUE),
                                                                     avg_drive.nsw = mean(shortest_time[GCC_NAME == "Rest of NSW"],
                                                                                          na.rm = TRUE),
                                                                     avg_drive.act = mean(shortest_time[GCC_NAME == "Australian Capital Territory"],
                                                                                          na.rm = TRUE),
                                                                     ) %>% t(),
                        # Longest driving time to an ACHD clinic - current clinics
                        long_drive.old = area.achd %>% mutate(shortest_time = as.numeric(shortest_time, 'hours')) %>%
                                                           summarise(max_drive.all = max(shortest_time, na.rm = TRUE),
                                                                     max_drive.syd = max(shortest_time[GCC_NAME == "Greater Sydney"],
                                                                                          na.rm = TRUE),
                                                                     max_drive.nsw = max(shortest_time[GCC_NAME == "Rest of NSW"],
                                                                                          na.rm = TRUE),
                                                                     max_drive.act = max(shortest_time[GCC_NAME == "Australian Capital Territory"],
                                                                                          na.rm = TRUE),
                                                                     ) %>% t(),
                        # Number of Patients within 1 hour drive - new clinics
                        hr.patient.new = drive.polys()@data %>% filter(as.numeric(shortest_time, "hours") <= 1) %>%
                                                    summarise(
                                                    hr.no = sum(ACHD_count), # All Patients
                                                    hr.syd = sum(ACHD_count[GCC_NAME16 == "Greater Sydney"]), # Sydney
                                                    hr.nsw = sum(ACHD_count[GCC_NAME16 == "Rest of NSW"]), # NSW
                                                    hr.act = sum(ACHD_count[GCC_NAME16 == "Australian Capital Territory"]) # ACT
                                                    ) %>% t(),
                        # Average driving time to an ACHD clinic - new clinics
                        avg_drive.new = drive.polys()@data %>% mutate(shortest_time = as.numeric(shortest_time, 'hours')) %>%
                                                           summarise(avg_drive.all = mean(shortest_time, na.rm = TRUE),
                                                                     avg_drive.syd = mean(shortest_time[GCC_NAME16 == "Greater Sydney"],
                                                                                          na.rm = TRUE),
                                                                     avg_drive.nsw = mean(shortest_time[GCC_NAME16 == "Rest of NSW"],
                                                                                          na.rm = TRUE),
                                                                     avg_drive.act = mean(shortest_time[GCC_NAME16 == "Australian Capital Territory"],
                                                                                          na.rm = TRUE),
                                                                     ) %>% t(),
                        # Longest driving time to an ACHD clinic - new clinics
                        long_drive.new = drive.polys()@data %>% mutate(shortest_time = as.numeric(shortest_time, 'hours')) %>%
                                                           summarise(max_drive.all = max(shortest_time, na.rm = TRUE),
                                                                     max_drive.syd = max(shortest_time[GCC_NAME16 == "Greater Sydney"],
                                                                                          na.rm = TRUE),
                                                                     max_drive.nsw = max(shortest_time[GCC_NAME16 == "Rest of NSW"],
                                                                                          na.rm = TRUE),
                                                                     max_drive.act = max(shortest_time[GCC_NAME16 == "Australian Capital Territory"],
                                                                                          na.rm = TRUE),
                                                                     ) %>% t()
                                    ) %>%
                            mutate(hr.percent.old = round( ( hr.patient.old / no.patient ) * 100, digits = 2 ),
                                   hr.percent.new = round( ( hr.patient.new / no.patient ) * 100, digits = 2 ),
                                   avg_drive.old = round( avg_drive.old, digits = 2),
                                   long_drive.old = round( long_drive.old, digits = 2),
                                   avg_drive.new = round( avg_drive.new, digits = 2),
                                   long_drive.new = round( long_drive.new, digits = 2)
                                   ) %>%
                            select(no.patient, hr.percent.old, avg_drive.old, long_drive.old, 
                                   hr.percent.new, avg_drive.new, long_drive.new)

row.names(pt.summary.compare) <- c("All", "Great Sydney", "Rest of NSW", "Australian Capital Territory")
```

``` {r, echo = FALSE}
# Display the Table Nicely
pt.summary.compare %>%
  kbl(booktabs = T,
      align=rep('r', 7), # right align the data
      # Add nice Column Names
      col.names = c("Patients (n)",
                    "Patients within 1hr (%)",
                    "Average Drive to ACHD Clinic (hrs)",
                    "Longest Drive to ACHD Clinic (hrs)",
                    "Patients within 1hr (%)",
                    "Average Drive to ACHD Clinic (hrs)",
                    "Longest Drive to ACHD Clinic (hrs)"),
      # Table caption
      caption = "\\textbf{Number of patients, and driving time to current clinics and new clinics;
                                 by region}") %>%
  add_header_above(c(" " = 2, "Current Clinics" = 3, "New Clinics" = 3)) %>%
  kable_styling(full_width = F,
                latex_options = c("striped", "hold_position", "scale_down"),
                position = "left"
                )%>%
        column_spec(column = 1, width = "2cm") %>% 
        column_spec(column = 2, width = "1cm") %>% 
        column_spec(column = 3, width = "2cm") %>% 
        column_spec(column = 4, width = "2cm") %>% 
        column_spec(column = 5, width = "2cm") %>% 
        column_spec(column = 6, width = "2cm") %>% 
        column_spec(column = 7, width = "2cm") %>%
        column_spec(column = 8, width = "2cm")
```

